project_id = "crkhkzcscgoeyspaczux"

[functions.wallet-nonce]
verify_jwt = false

[functions.prove-control]
verify_jwt = false

[functions.submit-kyb]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = true

[functions.monitor-blockchain]
verify_jwt = false

[functions.settle-payment]
verify_jwt = false

[functions.deliver-webhooks]
verify_jwt = false
